### ISSUE TITLE
ACCESS/Updates to access (Change Request)

### ISSUE THREAD

**Issue by Adebukola** [Mandiklopper/UBA-HR-Queries-Issues#73]
Please see attached document
[SAGE X3 People_UBA_Change Request_Template_Nov 20 Access Changes.docx](https://github.com/Mandiklopper/UBA-HR-Queries-Issues/files/1487063/SAGE.X3.People_UBA_Change.Request_Template_Nov.20.Access.Changes.docx)

**Comment by chidiif** [comment]
Done. @Adebukola, Kindly assist to test and confirm it is setup as requested.

**Comment by Adebukola** [comment]
Nwamaka Kalu is still unable to enter account numbers on the Employee link.  Please check

**Comment by roberteta** [comment]
She has successfully entered account numbers
