### ISSUE TITLE
ACCESS/Inability to Access People Connect - Chidiebere Anindu

### ISSUE THREAD

**Issue by chidiif** [Mandiklopper/UBA-HR-Queries-Issues#76]
Good morning.

I can’t seem to login in to the website.

Kindly advise please.

**Comment by chidiif** [comment]
Done. @Adebukola , Kindly advise user to test again.

**Comment by roberteta** [comment]
User is still unable to login. Once he enters his username and password and clicks on the login button, it clears the usernae and password fields

**Comment by roberteta** [comment]
User is ok now. Will reconfirm again tomorrow morning and ascertain the role of AD import to X3
